---
pipeline:
  name: DevQAPipeline
  description: Dev / QA Env Pipeline for Product X
  processflow：
    - verify
    - preBuildTest
    - build
    - postBuildTest
    - parallel：
        - series：
            - deployDevEnv
            - devFuncTest
        - series：
            - deployQAEnv
            - qaFuncTest
shared:
  environment:
    GO_ENV: test
    TRIGGER_BRANCH: master
  matrix:
    GO_VERSION: ['1.7.4', '1.6.4']
proceses:
  verify:
    category: 'CodeCheck'
    stage：'Build'
    type: 'SonarQube_FingBugs'
    parameters:
      engine: 'FindBugs'
  preBuildTest：
    category: 'UnitTest'
    stage：'Build'
    type: 'Go_UnitTest'
  build:
    category: 'CodeBuild'
    stage：'Build'
    type: 'Go_Build'
    parameters:
      GOARCH: 'amd64'
  postBuildTest:
    category: 'FuncTest'
    stage：'Test'
    type: 'API_Test'
    parameters:
      TEST_SUITE_NAME: 'mininum_api_test'
  deployDevEnv:
    category: 'containerDeploy'
    stage：'Deploy'
    type: 'k8s_Deploy'
    parameters:
      descriptor: 'service_dev_env.yaml'
    environments: 'configMap_dev_env.yaml'
  devFuncTest:
    category: 'FuncTest'
    stage：'Test'
    type: 'API_Test'
    parameters:
      TEST_SUITE_NAME: 'dev_api_test'
  deployQAEnv:
    category: 'containerDeploy'
    stage：'Deploy'
    type: 'k8s_Deploy'
    parameters:
      descriptor: 'service_dev_env.yaml'
    environments: 'configMap_qa_env.yaml'
  qaFuncTest:
    category: 'FuncTest'
    stage：'Test'
    type: 'API_Test'
    parameters:
      TEST_SUITE_NAME: 'qa_api_test'
